version: "3.8"
services:
  # Сервис Postgres
  postgres:
    image: postgres:15
    container_name: contest_postgres
    environment:
      - POSTGRES_DB=contest_db
      - POSTGRES_USER=contest_user
      - POSTGRES_PASSWORD=contest_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d  # добавьте эту строку
    networks:
      - contest_network

  # Сервис Node.js (backend)
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: contest_backend
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=contest_db
      - POSTGRES_USER=contest_user
      - POSTGRES_PASSWORD=contest_pass
      - POSTGRES_PORT=5432
    depends_on:
      - postgres
    networks:
      - contest_network
  # Сервис фронтенда (Vue)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: contest_frontend
    ports:
      - "8080:80" # Nginx внутри контейнера слушает 80
    depends_on:
      - backend

networks:
  contest_network:
    driver: bridge

volumes:
  postgres_data:
