services:
  # Сервис Postgres
  postgres:
    image: postgres:15
    container_name: contest_postgres
    environment:
      - POSTGRES_DB=contest_db
      - POSTGRES_USER=contest_user
      - POSTGRES_PASSWORD=contest_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - contest_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U contest_user -d contest_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Сервис Node.js (backend)
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: contest_backend
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=contest_db
      - POSTGRES_USER=contest_user
      - POSTGRES_PASSWORD=contest_pass
      - POSTGRES_PORT=5432
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - contest_network
  # Сервис фронтенда (Vue)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: contest_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - contest_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro

networks:
  contest_network:
    driver: bridge

volumes:
  postgres_data:
