services:
  # PostgreSQL сервис
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=contest_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  # Redis сервис
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  # Loki сервис
  loki:
    image: grafana/loki:2.9.0
    user: root
    ports:
      - "3100:3100"
    volumes:
      - ./loki/config.yml:/config.yaml
      - loki_data:/loki
      - /etc/localtime:/etc/localtime:ro
    command: -config.file=/config.yaml -config.expand-env=true
    networks:
      - app-network

  # Promtail сервис
  promtail:
    image: grafana/promtail:2.9.0
    volumes:
      - ./promtail/config.yml:/etc/promtail/config.yml
      - ../backend/logs:/var/log/backend
      - /etc/localtime:/etc/localtime:ro
    command: -config.file=/etc/promtail/config.yml
    networks:
      - app-network
    depends_on:
      - loki

  # Grafana сервис
  grafana:
    image: grafana/grafana:10.0.0
    ports:
      - "3001:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - /etc/localtime:/etc/localtime:ro
    networks:
      - app-network
    depends_on:
      - loki

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  loki_data:
  grafana_data: 