auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

frontend:
  compress_responses: true
  log_queries_longer_than: 10s

frontend_worker:
  frontend_address: "127.0.0.1:9096"
  grpc_client_config:
    max_send_msg_size: 104857600  # 100MB в байтах

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  wal:
    enabled: true
    dir: /loki/wal

schema_config:
  configs:
    - from: 2020-05-15
      store: boltdb
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb:
    directory: /loki/index
  filesystem:
    directory: /loki/chunks

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  max_global_streams_per_user: 5000
  ingestion_rate_mb: 64
  ingestion_burst_size_mb: 128
  creation_grace_period: 24h
  max_entries_limit_per_query: 5000
  max_query_length: 721h
  max_query_parallelism: 32
  per_stream_rate_limit: 512KB
  per_stream_rate_limit_burst: 1MB
  ingestion_rate_strategy: global
  max_streams_per_user: 0
  max_line_size: 256KB
  split_queries_by_interval: 24h

chunk_store_config:
  max_look_back_period: 0s

table_manager:
  retention_deletes_enabled: false
  retention_period: 0s

query_range:
  align_queries_with_step: true
  max_retries: 5
  cache_results: true

querier:
  max_concurrent: 10
  query_timeout: 10m
  engine:
    timeout: 5m
    max_look_back_period: 5m 