server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: backend_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: backend_logs
          __path__: /var/log/backend/**/*.log
          app: backend
    pipeline_stages:
      - regex:
          expression: '\[(?P<timestamp>\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}.\d{3})\]\s+\[(?P<component>\w+)\]\s+\[(?P<level>\w+)\]\s+\[(?P<request_id>[^\]]+)\]\s+\[(?P<module>[^\]]+)\]\s+\[(?P<user>[^\]]+)\]\s+\[(?P<ip>[^\]]+)\]\s+\[(?P<message>[^\]]+)\]'
      - labels:
          level:
          component:
          request_id:
          user:
          ip:
      - timestamp:
          source: timestamp
          format: '2006-01-02 15:04:05.000'
      - output:
          source: message

  - job_name: audit_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: audit_logs
          __path__: /var/log/backend/audit-*.json
          app: backend
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
      - labels:
          level:
      - timestamp:
          source: timestamp
          format: RFC3339 